<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <RootNamespace>AppSupervisor.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AppSupervisor\AppSupervisor.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\AppSupervisor.Tests\M*.cs" Link="%(Filename)%(Extension)" />
    <Compile Include="..\AppSupervisor.Tests\N*.cs" Link="%(Filename)%(Extension)" />
    <Compile Include="..\AppSupervisor.Tests\O*.cs" Link="%(Filename)%(Extension)" />
    <Compile Include="..\AppSupervisor.Tests\P*.cs" Link="%(Filename)%(Extension)" />
    <Compile Include="..\AppSupervisor.Tests\R*.cs" Link="%(Filename)%(Extension)" />
    <Compile Include="..\AppSupervisor.Tests\S*.cs" Link="%(Filename)%(Extension)" />
    <Compile Include="..\AppSupervisor.Tests\T*.cs" Link="%(Filename)%(Extension)" />
    <Compile Include="..\AppSupervisor.Tests\V*.cs" Link="%(Filename)%(Extension)" />
    <Compile Include="..\AppSupervisor.Tests\W*.cs" Link="%(Filename)%(Extension)" />
    <Compile Include="..\AppSupervisor.Tests\X*.cs" Link="%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
